-- xray-timeline-patch v2.0.1
-- Character presence map and filter for the X-Ray plugin's plot timeline.
-- https://github.com/Pixxel123/xray-timeline-patch
-- Generated by tools/build.lua from src/. DO NOT EDIT DIRECTLY.
-- Requires: X-Ray plugin >= 26.9.4-beta; KOReader >= 2026.07 (tested). On an
-- incompatible plugin this patch logs one warning and leaves the stock
-- timeline untouched; older plugins can use release v1.0.0.

local Presence = (function()
-- Timeline presence map: pure layout logic, no UI dependencies.
-- Stateless, so M.name() not M:name(). Required directly, like xray_theme.
-- Name matching duplicates ChapterAnalyzer:findCharactersInText and is
-- case-insensitive to agree with it. No dependencies, so the spec can run
-- outside KOReader.
local M = {}

local BYTE_0, BYTE_9 = string.byte("0"), string.byte("9")
local BYTE_A, BYTE_Z = string.byte("A"), string.byte("Z")
local BYTE_a, BYTE_z = string.byte("a"), string.byte("z")
local BYTE_UNDERSCORE = string.byte("_")

-- ASCII only. CJK bytes are never word characters, so the boundary checks
-- always pass and matching falls back to plain substring search.
local function isWordByte(b)
    return b ~= nil and (
        (b >= BYTE_0 and b <= BYTE_9) or
        (b >= BYTE_A and b <= BYTE_Z) or
        (b >= BYTE_a and b <= BYTE_z) or
        b == BYTE_UNDERSCORE)
end

-- Whether the AI labelled this character a lead. The role field is free text,
-- so this is a hint, never a ranking.
local function isLead(role)
    return type(role) == "string" and role:lower():find("protagonist", 1, true) ~= nil
end

-- The last word of a multi-word name. Prose leans on surnames ("Holden's crew")
-- and the AI's alias list often omits them. Short ones collide too often to
-- guess from, so they are skipped, as in xray_data's frequency scorer.
local function surnameOf(name)
    if type(name) ~= "string" then return nil end
    local last = name:match("(%S+)$")
    if last and #last > 3 and last ~= name then return last end
    return nil
end

-- Lower-cased once per call rather than per chapter. Duplicates are dropped:
-- an alias that repeats the canonical name or the surname would otherwise buy a
-- second scan of every chapter for an answer the first scan already gave.
local function needlesFor(character, own_surname)
    local needles, seen = {}, {}
    local function add(text)
        if type(text) ~= "string" or text == "" then return end
        local lowered = text:lower()
        if seen[lowered] then return end
        seen[lowered] = true
        needles[#needles + 1] = {
            text = lowered,
            starts_word = isWordByte(lowered:byte(1)),
            ends_word = isWordByte(lowered:byte(#lowered)),
        }
    end
    add(character.name)
    for _, alias in ipairs(character.aliases or {}) do add(alias) end
    add(own_surname)
    return needles
end

-- Plain find, not a pattern, so names with metacharacters need no escaping.
-- Only an end that is itself a word character needs a boundary check, so a
-- name ending in ")" still matches.
local function containsNeedle(text, needle)
    local from = 1
    local len = #text
    while true do
        local s, e = text:find(needle.text, from, true)
        if not s then return false end
        local ok_before = not needle.starts_word or not isWordByte(text:byte(s - 1))
        local ok_after = not needle.ends_word or
            (e >= len or not isWordByte(text:byte(e + 1)))
        if ok_before and ok_after then return true end
        from = s + 1
    end
end

-- Which tracked characters are named in each event.
-- Returns matrix[row][character_name] = true.
-- The caller supplies already-filtered events, so row N is its event N.
-- Both the chapter title and the summary are searched.
function M.buildPresenceMatrix(events, characters)
    -- The name is this matrix's key, so a nameless entry is skipped.
    -- A surname shared by two characters identifies neither, so it is only a
    -- needle when one character owns it.
    local surnames, owners = {}, {}
    for i, character in ipairs(characters or {}) do
        local surname = surnameOf(character.name)
        surnames[i] = surname
        if surname then
            local key = surname:lower()
            owners[key] = (owners[key] or 0) + 1
        end
    end

    local needles = {}
    for i, character in ipairs(characters or {}) do
        if type(character.name) == "string" and character.name ~= "" then
            local surname = surnames[i]
            if surname and owners[surname:lower()] ~= 1 then surname = nil end
            needles[#needles + 1] =
                { name = character.name, list = needlesFor(character, surname) }
        end
    end

    local matrix = {}
    for row, entry in ipairs(events or {}) do
        local cell = {}
        local text = ((entry.chapter or "") .. "\n" .. (entry.event or "")):lower()
        for _, character in ipairs(needles) do
            for _, needle in ipairs(character.list) do
                if containsNeedle(text, needle) then
                    cell[character.name] = true
                    break
                end
            end
        end
        matrix[row] = cell
    end
    return matrix
end

-- Below this many characters, min_coverage is ignored. See coverageOrder.
local MIN_FILTERED_ROWS = 3

-- Characters that appear at all, most-present first. Shared by the filter
-- buttons, name gutter and grid rows, so a position always means the same
-- character. Ties break by first appearance then name, so the order does not
-- shuffle between rebuilds.
--
-- min_coverage drops walk-ons named in fewer than that many chapters, and
-- defaults to 1, which keeps everyone. It is ignored when fewer than
-- MIN_FILTERED_ROWS characters would survive: early in a book almost everyone
-- appears once, and an empty map is worse than a crowded one. A lead is kept
-- either way, since appearing in one fetched chapter does not make them minor.
function M.coverageOrder(matrix, characters, min_coverage)
    -- Keyed by name, matching the matrix, so two entries sharing one name draw
    -- one row rather than two identical ones. The same non-empty-string check
    -- as buildPresenceMatrix, so a nameless AI entry is skipped by both.
    -- lead is the union across those entries: the role sits on whichever one
    -- the AI wrote it on, and taking only the first would drop a protagonist
    -- the rule below is meant to keep.
    local by_name, entries = {}, {}
    for _, character in ipairs(characters or {}) do
        local name = character.name
        if type(name) == "string" and name ~= "" then
            local entry = by_name[name]
            if not entry then
                entry = { name = name, coverage = 0, first = nil, lead = false }
                by_name[name] = entry
                entries[#entries + 1] = entry
            end
            if isLead(character.role) then entry.lead = true end
        end
    end

    -- One pass over the matrix rather than a rescan per character. Rows are
    -- visited in order, so the first row to name someone is their first.
    for row = 1, #matrix do
        for name in pairs(matrix[row] or {}) do
            local entry = by_name[name]
            if entry then
                entry.coverage = entry.coverage + 1
                entry.first = entry.first or row
            end
        end
    end

    local stats = {}
    for _, entry in ipairs(entries) do
        if entry.coverage > 0 then stats[#stats + 1] = entry end
    end

    table.sort(stats, function(a, b)
        if a.coverage ~= b.coverage then return a.coverage > b.coverage end
        if a.first ~= b.first then return a.first < b.first end
        return a.name < b.name
    end)

    local order, kept = {}, {}
    for i, entry in ipairs(stats) do
        order[i] = entry.name
        if entry.coverage >= (min_coverage or 1) or entry.lead then
            kept[#kept + 1] = entry.name
        end
    end
    if #kept >= MIN_FILTERED_ROWS then return kept end
    return order
end

-- Ascending row indices where every selected character is present.
-- An empty selection means all rows.
function M.matchingChapters(matrix, selected)
    local out = {}
    for row = 1, #matrix do
        local all_present = true
        for _, name in ipairs(selected or {}) do
            if not (matrix[row] and matrix[row][name]) then
                all_present = false
                break
            end
        end
        if all_present then out[#out + 1] = row end
    end
    return out
end

-- Collapse a chapter-level matrix into at most n_buckets columns, so a long
-- book fits the screen without scrolling sideways.
-- chapter_matches is the row list from matchingChapters.
-- Returns the bucketed matrix, the matching bucket indices, and the ranges.
--
-- Presence can be bucketed, but crossings cannot. That is why this takes an
-- already resolved list of matching chapters rather than a selection.
-- Two characters in different chapters of one span have not met, so working
-- the crossings out from the bucketed matrix would report a meeting that
-- never happened.
function M.bucketMatrix(matrix, chapter_matches, n_buckets)
    local nrows = #matrix
    -- No chapters means no columns. The clamp below floors the count at one,
    -- which would otherwise invent a bucket spanning a chapter that is not there.
    if nrows == 0 then return {}, {}, {} end
    n_buckets = math.max(1, math.min(n_buckets or nrows, nrows))

    local matched_row = {}
    for _, idx in ipairs(chapter_matches or {}) do matched_row[idx] = true end

    local buckets, matches, ranges = {}, {}, {}
    for b = 1, n_buckets do
        -- Spread any remainder evenly rather than piling it into the last span.
        local first = math.floor((b - 1) * nrows / n_buckets) + 1
        local last = math.floor(b * nrows / n_buckets)
        if last < first then last = first end
        ranges[b] = { first = first, last = last }

        local cell, crossed = {}, false
        for row = first, last do
            for name in pairs(matrix[row] or {}) do cell[name] = true end
            if matched_row[row] then crossed = true end
        end
        buckets[b] = cell
        if crossed then matches[#matches + 1] = b end
    end

    return buckets, matches, ranges
end

-- Pixel height of a strip with this many rows. Exported so the strip
-- widget's scroll viewport cannot drift from what the renderers draw.
function M.stripHeight(n_rows, geom)
    return geom.top_padding + n_rows * geom.row_height + (geom.bottom_padding or 4)
end

local XML_ESCAPES = { ["&"] = "&amp;", ["<"] = "&lt;", [">"] = "&gt;", ['"'] = "&quot;" }

local function xmlEscape(text)
    return (tostring(text):gsub('[&<>"]', XML_ESCAPES))
end

local function svgOpen(w, h)
    return {
        string.format(
            '<svg xmlns="http://www.w3.org/2000/svg" width="%d" height="%d" viewBox="0 0 %d %d">',
            w, h, w, h),
        string.format('<rect class="bg" x="0" y="0" width="%d" height="%d" fill="white"/>', w, h),
    }
end

local function selectedSet(selected)
    local set = {}
    for _, name in ipairs(selected or {}) do set[name] = true end
    return set
end

-- The left gutter: one name per row, every row in `order`. Selected names
-- are bold on a shaded band. Split from the grid so it stays put while the
-- grid scrolls. Returns svg, width, height.
function M.buildStripNamesSVG(order, selected, geom)
    local is_selected = selectedSet(selected)
    local width, height = geom.name_width, M.stripHeight(#order, geom)
    local out = svgOpen(width, height)
    for r, name in ipairs(order) do
        local y = geom.top_padding + (r - 1) * geom.row_height + geom.row_height / 2
        if is_selected[name] then
            out[#out + 1] = string.format(
                '<rect class="band" x="0" y="%.1f" width="%d" height="%d" fill="#e3e6df"/>',
                y - geom.row_height / 2, width, geom.row_height)
        end
        out[#out + 1] = string.format(
            '<text class="cname" x="%.1f" y="%.1f" font-size="%d" text-anchor="end" fill="black"%s>%s</text>',
            width - 7, y + 3, geom.label_size + 2,
            is_selected[name] and ' font-weight="bold"' or "", xmlEscape(name))
    end
    out[#out + 1] = "</svg>"
    return table.concat(out, "\n"), width, height
end

-- The grid: columns as chapters (or bucketed spans), one row per name in
-- `order`. Returns svg, width, height.
--
-- Every row and every column stays while filtering, so the reader can see
-- where the matches fall against everyone else. Selected rows get a band,
-- matching columns a shade, and two or more selections a join line from the
-- first selected row to the last.
--
-- match_cols must be passed in. A bucketed matrix has already lost the
-- per-chapter detail, so the crossings cannot be worked out here.
function M.buildStripGridSVG(matrix, order, chapters, selected, geom, match_cols)
    local is_selected = selectedSet(selected)
    local filtering = selected ~= nil and #selected > 0

    local matches = {}
    for _, idx in ipairs(match_cols or {}) do matches[idx] = true end

    local nrows, ncols = #order, #chapters
    local width, height = ncols * geom.col_width, M.stripHeight(nrows, geom)
    local out = svgOpen(width, height)

    local function colX(i) return (i - 1) * geom.col_width + geom.col_width / 2 end
    local function rowY(r)
        return geom.top_padding + (r - 1) * geom.row_height + geom.row_height / 2
    end

    local first_sel, last_sel
    for r, name in ipairs(order) do
        if is_selected[name] then
            first_sel = first_sel or r
            last_sel = r
            out[#out + 1] = string.format(
                '<rect class="band" x="0" y="%.1f" width="%d" height="%d" fill="#e3e6df"/>',
                rowY(r) - geom.row_height / 2, width, geom.row_height)
        end
    end

    if filtering then
        local join = first_sel ~= nil and last_sel > first_sel
        for i = 1, ncols do
            if matches[i] then
                out[#out + 1] = string.format(
                    '<rect class="shade" x="%.1f" y="%.1f" width="%d" height="%.1f" fill="#bfc4b8"/>',
                    colX(i) - geom.col_width / 2, geom.top_padding,
                    geom.col_width, nrows * geom.row_height)
                if join then
                    out[#out + 1] = string.format(
                        '<line class="join" x1="%.1f" y1="%.1f" x2="%.1f" y2="%.1f" stroke="black" stroke-width="2"/>',
                        colX(i), rowY(first_sel), colX(i), rowY(last_sel))
                end
            end
        end
    end

    for r, name in ipairs(order) do
        for i = 1, ncols do
            if matrix[i] and matrix[i][name] then
                out[#out + 1] = string.format(
                    '<rect class="pip" x="%.1f" y="%.1f" width="%d" height="%d" fill="black"/>',
                    colX(i) - geom.marker / 2, rowY(r) - geom.marker / 2,
                    geom.marker, geom.marker)
            end
        end
    end

    out[#out + 1] = "</svg>"
    return table.concat(out, "\n"), width, height
end

-- Which row a tap lands on. y_rel is measured from the top of the names
-- image, in the units geom uses. nil above the first row or past the last.
function M.rowAt(y_rel, geom, n_rows)
    if type(y_rel) ~= "number" or y_rel < geom.top_padding then return nil end
    local row = math.floor((y_rel - geom.top_padding) / geom.row_height) + 1
    if row < 1 or row > (n_rows or 0) then return nil end
    return row
end

-- The filter caption: names joined by a middle dot, then the number of
-- matching chapters in the stock title's "(N)" style, so it needs no
-- translated words. Empty when nothing is selected.
function M.captionText(selected, n_matches)
    if not selected or #selected == 0 then return "" end
    return table.concat(selected, " \u{00B7} ") .. " (" .. tostring(n_matches or 0) .. ")"
end

return M

end)()

local TRANSLATIONS = (function()
-- 2 timeline keys x 17 languages, maintained here in-repo (not generated):
-- the plugin's .po files carry neither msgid, the fork branch that added them
-- being gone, so tools/extract_translations.lua can regenerate this table
-- only from a languages dir that has both. Every string below is what the
-- plugin's own .po parse would produce, byte for byte.
return {
    ["ar"] = {
        ["menu_timeline_all"] = "الكل",
        ["menu_timeline_presence_map"] = "استخدام خريطة الحضور في الخط الزمني",
    },
    ["de"] = {
        ["menu_timeline_all"] = "Alle",
        ["menu_timeline_presence_map"] = "Präsenzkarte in der Zeitleiste verwenden",
    },
    ["en"] = {
        ["menu_timeline_all"] = "All",
        ["menu_timeline_presence_map"] = "Use Presence Map in Timeline",
    },
    ["es"] = {
        ["menu_timeline_all"] = "Todos",
        ["menu_timeline_presence_map"] = "Usar mapa de presencia en la cronología",
    },
    ["fr"] = {
        ["menu_timeline_all"] = "Tous",
        ["menu_timeline_presence_map"] = "Utiliser la carte de présence dans la chronologie",
    },
    ["hu"] = {
        ["menu_timeline_all"] = "Mind",
        ["menu_timeline_presence_map"] = "Jelenléti térkép használata az idővonalon",
    },
    ["id"] = {
        ["menu_timeline_all"] = "Semua",
        ["menu_timeline_presence_map"] = "Gunakan peta kehadiran di lini masa",
    },
    ["it"] = {
        ["menu_timeline_all"] = "Tutti",
        ["menu_timeline_presence_map"] = "Usa la mappa delle presenze nella cronologia",
    },
    ["ja"] = {
        ["menu_timeline_all"] = "すべて",
        ["menu_timeline_presence_map"] = "タイムラインで登場マップを使用",
    },
    ["nl"] = {
        ["menu_timeline_all"] = "Alle",
        ["menu_timeline_presence_map"] = "Aanwezigheidskaart in tijdlijn gebruiken",
    },
    ["pl"] = {
        ["menu_timeline_all"] = "Wszystkie",
        ["menu_timeline_presence_map"] = "Użyj mapy obecności na osi czasu",
    },
    ["pt_br"] = {
        ["menu_timeline_all"] = "Todos",
        ["menu_timeline_presence_map"] = "Usar mapa de presença na linha do tempo",
    },
    ["ru"] = {
        ["menu_timeline_all"] = "Все",
        ["menu_timeline_presence_map"] = "Использовать карту присутствия на шкале времени",
    },
    ["sr"] = {
        ["menu_timeline_all"] = "Сви",
        ["menu_timeline_presence_map"] = "Користи мапу присуства на временској оси",
    },
    ["tr"] = {
        ["menu_timeline_all"] = "Tümü",
        ["menu_timeline_presence_map"] = "Zaman çizelgesinde varlık haritasını kullan",
    },
    ["uk"] = {
        ["menu_timeline_all"] = "Усі",
        ["menu_timeline_presence_map"] = "Використовувати карту присутності на шкалі часу",
    },
    ["zh_CN"] = {
        ["menu_timeline_all"] = "全部",
        ["menu_timeline_presence_map"] = "在时间线中使用出场图",
    },
}

end)()

local Strip = (function()
-- Presence strip for the stock timeline overlay (xray_entity_list.lua).
-- Builds the widget the adapter slots under the overlay's header, owns the
-- cache of rendered bitmaps, and knows the shape of the stock tree it goes
-- into. It knows nothing about the plugin: the caller passes data and an
-- on_toggle callback.
--
-- NOT loadable standalone: the build prepends the chunk-local `Presence`
-- (src/xray_presencemap.lua). The spec sets _G.Presence instead.

local Blitbuffer          = require("ffi/blitbuffer")
local Button              = require("ui/widget/button")
local CenterContainer     = require("ui/widget/container/centercontainer")
local Font                = require("ui/font")
local Geom                = require("ui/geometry")
local GestureRange        = require("ui/gesturerange")
local HorizontalGroup     = require("ui/widget/horizontalgroup")
local HorizontalSpan      = require("ui/widget/horizontalspan")
local ImageWidget         = require("ui/widget/imagewidget")
local InputContainer      = require("ui/widget/container/inputcontainer")
local LeftContainer       = require("ui/widget/container/leftcontainer")
local LineWidget          = require("ui/widget/linewidget")
local ScrollableContainer = require("ui/widget/container/scrollablecontainer")
local Screen              = require("device").screen
local TextWidget          = require("ui/widget/textwidget")
local VerticalGroup       = require("ui/widget/verticalgroup")
local VerticalSpan        = require("ui/widget/verticalspan")

local M = {}

M.VISIBLE_ROWS = 4
-- Only long-press is left to the rows underneath; a drag (pan) and a flick
-- (swipe) both scroll the strip. ScrollableContainer acts on a pan only when
-- the touch began inside it, so the list below still pans freely.
local IGNORED_GESTURES = { "hold", "hold_release", "hold_pan" }

local function sc(n) return Screen:scaleBySize(n) end

-- All in scale units. name_width and the row metrics are what the SVG
-- builders draw with; col_width is filled in once the column count is known.
local function geometry(sw, scrolls)
    local pad = sc(6)
    local sbw = scrolls and ScrollableContainer:getScrollbarWidth() or 0
    local name_width = math.floor(sw * 0.22)
    local viewport_w = sw - pad * 2 - name_width - sbw
    return {
        pad = pad,
        viewport_w = viewport_w,
        max_cols = math.max(1, math.floor(viewport_w / sc(16))),
        name_width = name_width,
        row_height = sc(20),
        top_padding = sc(6),
        bottom_padding = sc(4),
        marker = sc(9),
        label_size = sc(9),
    }
end

function M.freeBitmaps(overlay)
    local cache = overlay._presence_bitmaps
    overlay._presence_bitmaps = nil
    if not cache then return end
    for _, key in ipairs({ "names", "grid" }) do
        local bb = cache[key]
        if bb and bb.free then bb:free() end
    end
end

-- A ScrollableContainer allocates a screen-sized offscreen Blitbuffer on its
-- first paint and frees it in onCloseWidget (its GC finalizer is a backstop
-- the collector does not pace, C heap being invisible to it). Every rebuild
-- makes a new container, so close the one it replaces.
function M.releaseWidgets(overlay)
    local widgets = overlay._presence_widgets
    overlay._presence_widgets = nil
    if not widgets then return end
    local scroller = widgets.scroller
    if scroller and scroller.onCloseWidget then scroller:onCloseWidget() end
end

-- Rasterize each half at exactly its own size; a mismatch would send
-- renderimage down its scaling path and blur the pips.
local function render(order, selected, matrix, columns, match_cols, geom)
    local RenderImage = require("ui/renderimage")
    local names_svg, nw, nh = Presence.buildStripNamesSVG(order, selected, geom)
    local grid_svg, gw, gh = Presence.buildStripGridSVG(
        matrix, order, columns, selected, geom, match_cols)
    local ok_n, names_bb = pcall(RenderImage.renderImageData, RenderImage,
        names_svg, #names_svg, false, nw, nh)
    local ok_g, grid_bb = pcall(RenderImage.renderImageData, RenderImage,
        grid_svg, #grid_svg, false, gw, gh)
    if ok_n and names_bb and ok_g and grid_bb then
        return { names = names_bb, grid = grid_bb, height = nh }
    end
    if ok_n and names_bb and names_bb.free then names_bb:free() end
    if ok_g and grid_bb and grid_bb.free then grid_bb:free() end
    return nil
end

-- Bitmaps live on the overlay across its rebuilds (every page turn and
-- d-pad move rebuilds the whole tree) and are replaced when the key changes.
local function bitmapsFor(overlay, key, ...)
    local cache = overlay._presence_bitmaps
    if cache and cache.key == key then return cache end
    M.freeBitmaps(overlay)
    cache = render(...)
    if cache then
        cache.key = key
        overlay._presence_bitmaps = cache
    end
    return cache
end

-- The name gutter as a tap target. paintTo records where it was drawn, so
-- a tap's y can be turned into a row even inside a scrolled container.
local function namesWidget(bb, geom, order, on_toggle)
    local image = ImageWidget:new{ image = bb, image_disposable = false }
    local names = InputContainer:new{ image }
    local size = image:getSize()
    names.dimen = Geom:new{ x = 0, y = 0, w = size.w, h = size.h }
    names.ges_events = {
        Tap = { GestureRange:new{ ges = "tap", range = function() return names.dimen end } },
    }
    function names:getSize() return image:getSize() end
    function names:paintTo(target, x, y)
        local s = image:getSize()
        self.dimen = Geom:new{ x = x, y = y, w = s.w, h = s.h }
        image:paintTo(target, x, y)
    end
    function names:onTap(_, ges)
        local row = Presence.rowAt(ges.pos.y - self.dimen.y, geom, #order)
        if row then on_toggle(order[row]) end
        return true
    end
    return names
end

-- The band has to be at least as tall as the button: LeftContainer centres
-- its child on dimen.h without growing, so a taller button would spill past
-- the band and have its bottom border painted over by the body below.
local function captionHeight(all_button)
    return math.max(sc(24), all_button:getSize().h + sc(4))
end

local function captionRow(sw, text, all_button, cap_h)
    local label = TextWidget:new{
        text = text,
        face = Font:getFace("cfont", 13),
        bold = true,
        fgcolor = Blitbuffer.COLOR_BLACK,
        max_width = sw - sc(40) - all_button:getSize().w,
    }
    local gap = math.max(sc(8), sw - sc(32) - label:getSize().w - all_button:getSize().w)
    return LeftContainer:new{
        dimen = Geom:new{ w = sw, h = cap_h },
        HorizontalGroup:new{
            align = "center",
            HorizontalSpan:new{ width = sc(16) },
            label,
            HorizontalSpan:new{ width = gap },
            all_button,
        },
    }
end

-- ctx: data {matrix, order, chapters}, selected (names), matches (row
-- indices from Presence.matchingChapters), sw (px), all_label,
-- on_toggle(name or nil for "All"), scroll (saved offset or nil).
-- Returns widget, height  or  nil, reason.
function M.build(overlay, ctx)
    -- Safe here: the caller has already read the outgoing scroll offset into
    -- ctx.scroll, and every path out of this function replaces the widgets.
    M.releaseWidgets(overlay)
    local order, selected = ctx.data.order, ctx.selected
    local n_rows = #order
    local scrolls = n_rows > M.VISIBLE_ROWS
    local filtering = #selected > 0
    local sw = ctx.sw
    local geom = geometry(sw, scrolls)

    -- One column per chapter while they stay at least 16 units wide; past
    -- that each column covers a span so the whole book still fits.
    local matrix, columns, match_cols = ctx.data.matrix, ctx.data.chapters, ctx.matches
    if #columns > geom.max_cols then
        matrix, match_cols, columns = Presence.bucketMatrix(matrix, ctx.matches, geom.max_cols)
    end
    geom.col_width = math.floor(geom.viewport_w / math.max(1, #columns))

    local key = table.concat(selected, "\n") .. "|" .. tostring(sw)
    local bbs = bitmapsFor(overlay, key, order, selected, matrix, columns, match_cols, geom)
    if not bbs then
        return nil, "strip render failed"
    end

    local widgets = { names = namesWidget(bbs.names, geom, order, ctx.on_toggle) }
    local body = HorizontalGroup:new{
        align = "top",
        HorizontalSpan:new{ width = geom.pad },
        widgets.names,
        ImageWidget:new{ image = bbs.grid, image_disposable = false },
    }

    local parts = VerticalGroup:new{ align = "left" }
    local height = 0

    if filtering then
        widgets.all = Button:new{
            text = ctx.all_label,
            show_parent = overlay, -- onTapSelectButton refreshes show_parent
            text_font_size = 13,
            padding = sc(2),
            bordersize = sc(1),
            radius = sc(4),
            callback = function() ctx.on_toggle(nil) end,
        }
        local cap_h = captionHeight(widgets.all)
        table.insert(parts, captionRow(sw,
            Presence.captionText(selected, #ctx.matches), widgets.all, cap_h))
        height = height + cap_h
    end

    if scrolls then
        local view_h = Presence.stripHeight(M.VISIBLE_ROWS, geom)
        local scroller = ScrollableContainer:new{
            dimen = Geom:new{ w = sw, h = view_h },
            ignore_events = IGNORED_GESTURES,
            show_parent = overlay,
            body,
        }
        if ctx.scroll then
            -- A filter change cannot shrink the strip (rows never hide), but
            -- clamp anyway so a stale offset can never scroll past the end.
            local max_offset = math.max(0, bbs.height - view_h)
            scroller:setScrolledOffset(Geom:new{
                x = 0, y = math.max(0, math.min(ctx.scroll.y or 0, max_offset)) })
        end
        widgets.scroller = scroller
        table.insert(parts, scroller)
        height = height + view_h
    else
        table.insert(parts, body)
        height = height + bbs.height
    end

    table.insert(parts, CenterContainer:new{
        dimen = Geom:new{ w = sw, h = sc(1) },
        LineWidget:new{
            background = Blitbuffer.Color8(180),
            dimen = Geom:new{ w = sw - sc(32), h = sc(1) },
        },
    })
    table.insert(parts, VerticalSpan:new{ width = sc(4) })
    height = height + sc(1) + sc(4)

    overlay._presence_widgets = widgets
    return parts, height
end

-- Slot the strip into the tree the beta's buildUI builds:
--   overlay[1]        OverlapGroup { dimen }
--     [1]             main surface FrameContainer { height, [1] = VerticalGroup { header, list } }
--     [2]             BottomContainer { dimen } holding the footer
-- The stock code was run with a screen shorter by the strip's height, so
-- every height it recorded is put back to full_h here.
function M.insert(overlay, strip, full_h)
    local top = overlay[1]
    if type(top) ~= "table" or type(top.dimen) ~= "table" then return false end
    local surface, footer = top[1], top[2]
    if type(surface) ~= "table" or type(surface.height) ~= "number" then return false end
    if type(footer) ~= "table" or type(footer.dimen) ~= "table" then return false end
    local vg = surface[1]
    if type(vg) ~= "table" or #vg ~= 2 then return false end
    if type(overlay.dimen) ~= "table" then return false end

    table.insert(vg, 2, strip)
    if vg.resetLayout then vg:resetLayout() end
    surface.height = full_h
    top.dimen.h = full_h
    top._size = nil
    footer.dimen.h = full_h
    overlay.dimen.h = full_h
    return true
end

return M

end)()

-- Adapter for xray-timeline-patch v2. NOT loadable standalone: the build
-- prepends the chunk-locals `Presence` (src/xray_presencemap.lua),
-- `TRANSLATIONS` (src/translations.lua) and `Strip`
-- (src/xray_timeline_strip.lua). tools/build.lua concatenates them.
--
-- The plugin's showTimeline is left alone. The stock EntityListOverlay
-- class is decorated instead: prepareItems gets a character filter, buildUI
-- gets the presence strip under the header, onCloseWidget frees the strip's
-- bitmaps. Every other list screen, and every plugin too old to have the
-- overlay, is untouched.

local UIManager = require("ui/uimanager")
local logger    = require("logger")

local MIN_CHAPTER_COVERAGE = 2 -- a character in fewer chapters is a walk-on
local SETTING = "timeline_presence_map"

local function warn(msg) logger.warn("xray-timeline-patch: " .. msg) end

-- Warnings that would repeat on every rebuild are logged once per session.
local warned = {}
local function warnOnce(key, msg)
    if warned[key] then return end
    warned[key] = true
    warn(msg)
end

-- Resolve the require() prefix for the plugin's own modules at call time.
-- Today plugin dirs sit bare on package.path (pluginloader.lua appends them,
-- so the prefix is ""); the scan keeps working if that ever changes. Lazy
-- because the plugin is not loaded yet when this patch file runs.
local plugin_prefix
local function pluginRequire(mod)
    if plugin_prefix == nil then
        plugin_prefix = ""
        for name in pairs(package.loaded) do
            local p = name:match("^(.*)xray_ui$")
            if p then plugin_prefix = p; break end
        end
    end
    return require(plugin_prefix .. mod)
end

-- Installed only if the plugin doesn't already have it.
local function settingEnabled(self, key, default)
    local settings = self.ai_helper and self.ai_helper.settings
    local value = settings and settings[key]
    if value == nil then return default == true end
    return value ~= false
end

local function presenceMapEnabled(self)
    return self:settingEnabled(SETTING, true)
end

-- Absent-only injection: official upstream strings win if these keys ever
-- ship in the plugin's .po files. English is the base for every language
-- because loc:t() returns the raw key (never nil) for a missing msgid, so
-- the code's `or "English"` fallbacks cannot fire.
local function injectTranslations(self)
    local loc = self.loc
    if not loc or type(loc.translations) ~= "table" then return end
    local exact = TRANSLATIONS[loc.current_language] or {}
    for key, en_value in pairs(TRANSLATIONS.en) do
        if loc.translations[key] == nil then
            loc.translations[key] = exact[key] or en_value
        end
    end
end

-- Per-overlay presence data, computed once per open. The stock showTimeline
-- has already assigned pages and sorted plugin.timeline before building the
-- overlay, so raw_items is in display order and needs no further work.
local function ensureData(overlay)
    if overlay._presence then return overlay._presence end
    local events, chapters = {}, {}
    for _, ev in ipairs(overlay.raw_items or {}) do
        if ev.source ~= "series_prior" then
            events[#events + 1] = ev
            chapters[#chapters + 1] = ev.chapter or ""
        end
    end
    local characters = overlay.plugin.characters or {}
    local matrix = Presence.buildPresenceMatrix(events, characters)
    overlay._presence = {
        events = events,
        chapters = chapters,
        matrix = matrix,
        order = Presence.coverageOrder(matrix, characters, MIN_CHAPTER_COVERAGE),
    }
    return overlay._presence
end

local function isActive(overlay)
    local plugin = overlay.plugin
    return overlay.mode == "timeline" and plugin ~= nil
        and type(plugin.presenceMapEnabled) == "function" and plugin:presenceMapEnabled()
end

-- The filter lives on the plugin so reopening the timeline keeps it. Names
-- with no row here (another book, or a character merged away since) are
-- dropped: there would be no way to tap them off again.
local function currentFilter(overlay, data)
    local plugin = overlay.plugin
    local has_row = {}
    for _, name in ipairs(data.order) do has_row[name] = true end
    local kept = {}
    for _, name in ipairs(plugin.timeline_filter or {}) do
        if has_row[name] then kept[#kept + 1] = name end
    end
    plugin.timeline_filter = kept
    return kept
end

local function wrapPrepareItems(Overlay)
    local orig = Overlay.prepareItems
    Overlay.prepareItems = function(self, ...)
        orig(self, ...)
        if not isActive(self) then return end
        local data = ensureData(self)
        local filter = currentFilter(self, data)
        if #filter == 0 then return end
        local keep = {}
        for _, row in ipairs(Presence.matchingChapters(data.matrix, filter)) do
            keep[data.events[row]] = true
        end
        local kept = {}
        for _, item in ipairs(self.items or {}) do
            if keep[item] then kept[#kept + 1] = item end
        end
        self.items = kept
    end
end

-- A tap on a name, or on "All" (name == nil). Rebuilds the way the stock
-- prior-books toggle does: page one, re-filter, re-layout, repaint.
local function toggle(overlay, name)
    local plugin = overlay.plugin
    if name == nil then
        plugin.timeline_filter = {}
    else
        local kept, removed = {}, false
        for _, n in ipairs(plugin.timeline_filter or {}) do
            if n == name then removed = true else kept[#kept + 1] = n end
        end
        if not removed then kept[#kept + 1] = name end
        plugin.timeline_filter = kept
    end
    overlay.current_page = 1
    overlay:prepareItems()
    overlay:buildUI()
    UIManager:setDirty(overlay, "ui")
end

local function wrapBuildUI(Overlay)
    local orig = Overlay.buildUI
    Overlay.buildUI = function(self, ...)
        -- A tree shape rejected once will not be recognised on a later
        -- rebuild either, so stop building a strip and running stock twice.
        if warned.layout or not isActive(self) then return orig(self, ...) end
        local data = ensureData(self)
        if #data.order == 0 or #data.chapters == 0 then return orig(self, ...) end

        -- The timeline can open from a gesture without the menu ever being
        -- built, so the "All" label is injected here too.
        injectTranslations(self.plugin)
        local filter = currentFilter(self, data)
        local widgets = self._presence_widgets
        local scroller = widgets and widgets.scroller
        local loc = self.plugin.loc
        -- Strip.build runs inside the overlay's init, so anything that threw
        -- in there would take KOReader's main loop down with it.
        local built, strip, height = pcall(Strip.build, self, {
            data = data,
            selected = filter,
            matches = Presence.matchingChapters(data.matrix, filter),
            sw = self.sw,
            scroll = scroller and scroller.getScrolledOffset and scroller:getScrolledOffset() or nil,
            all_label = (loc and loc:t("menu_timeline_all")) or "All",
            on_toggle = function(name)
                local ok, err = pcall(toggle, self, name)
                if not ok then warn("filter toggle failed: " .. tostring(err)) end
            end,
        })
        if not built then
            warnOnce("render", "strip build failed: " .. tostring(strip)
                .. " - showing the stock timeline without the map")
            Strip.releaseWidgets(self)
            return orig(self, ...)
        end
        if not strip then
            warnOnce("render", tostring(height) .. " - showing the stock timeline without the map")
            return orig(self, ...)
        end

        -- Stock budgets its rows from self.sh. Lend it a screen shorter by
        -- the strip, so the strip's height comes out of the rows, then put
        -- the real height back whatever happened.
        local full_h = self.sh
        self.sh = full_h - height
        local ok, err = pcall(orig, self, ...)
        self.sh = full_h
        if not ok then error(err, 0) end

        if not Strip.insert(self, strip, full_h) then
            warnOnce("layout", "overlay layout not recognised - showing the stock timeline without the map")
            Strip.releaseWidgets(self)
            return orig(self, ...)
        end
    end
end

local function wrapOnCloseWidget(Overlay)
    local orig = Overlay.onCloseWidget
    Overlay.onCloseWidget = function(self, ...)
        Strip.freeBitmaps(self)
        Strip.releaseWidgets(self)
        if orig then return orig(self, ...) end
    end
end

local function menuEntry(self)
    return {
        text = (self.loc and self.loc:t("menu_timeline_presence_map"))
            or "Use Presence Map in Timeline",
        checked_func = function() return self:presenceMapEnabled() end,
        callback = function()
            if self.ai_helper and self.ai_helper.settings then
                local ok, err = pcall(function()
                    self.ai_helper:saveSettings({ [SETTING] = not self:presenceMapEnabled() })
                    -- Rebuild if the timeline is open behind this menu.
                    if self.timeline_menu then self:showTimeline() end
                end)
                if not ok then warn("presence map toggle failed: " .. tostring(err)) end
            end
        end,
        separator = true,
    }
end

local function missingCapability(XRayPlugin)
    for _, name in ipairs({ "getSubMenuItems", "showTimeline" }) do
        if type(XRayPlugin[name]) ~= "function" then return "method " .. name end
    end
    local ok, Overlay = pcall(pluginRequire, "xray_entity_list")
    if not ok or type(Overlay) ~= "table" then
        return "module xray_entity_list (needs plugin 26.9.4-beta or newer)"
    end
    for _, name in ipairs({ "prepareItems", "buildUI" }) do
        if type(Overlay[name]) ~= "function" then return "method xray_entity_list." .. name end
    end
    if not pcall(require, "ui/renderimage") then return "module ui/renderimage" end
    return nil, Overlay
end

local function patch_fn(XRayPlugin)
    if XRayPlugin.__timeline_patch_applied then return end
    local missing, Overlay = missingCapability(XRayPlugin)
    if missing then
        warn("missing " .. missing .. " - leaving the stock timeline in place")
        return
    end
    XRayPlugin.__timeline_patch_applied = true

    if XRayPlugin.presenceMapEnabled == nil then
        XRayPlugin.presenceMapEnabled = presenceMapEnabled
    end
    if XRayPlugin.settingEnabled == nil then
        XRayPlugin.settingEnabled = settingEnabled
    end

    local orig_getSubMenuItems = XRayPlugin.getSubMenuItems
    XRayPlugin.getSubMenuItems = function(self, ...)
        injectTranslations(self)
        local items = orig_getSubMenuItems(self, ...)
        if type(items) == "table" then
            table.insert(items, menuEntry(self))
        end
        return items
    end

    -- The overlay module is shared by every plugin instance; wrap it once.
    if not Overlay.__timeline_patch_applied then
        Overlay.__timeline_patch_applied = true
        wrapPrepareItems(Overlay)
        wrapBuildUI(Overlay)
        wrapOnCloseWidget(Overlay)
    end
end

local ok, userpatch = pcall(require, "userpatch")
if not ok or type(userpatch) ~= "table" or not userpatch.registerPatchPluginFunc then
    return
end
userpatch.registerPatchPluginFunc("xray", patch_fn)
