-- Concatenates src/ into patches/2-xray-timeline-presence-map.lua.
-- Run from the repo root: luajit tools/build.lua

local PATCH_VERSION = "1.0.0"
local SOURCE_COMMIT = "c082f69"   -- timeline-presence-map commit the port tracks
local PLUGIN_FLOOR  = "26.7.27"   -- bounded by xray_utils.flattenTOC, first shipped in 26.7.27

local function slurp(path)
    local f = assert(io.open(path, "r"), "missing " .. path)
    local s = f:read("*a")
    f:close()
    return s
end

local header = string.format([[
-- xray-timeline-patch v%s
-- Scrolling timeline with a character presence map for the KOReader X-Ray plugin.
-- https://github.com/Pixxel123/xray-timeline-patch
-- Generated by tools/build.lua from src/ (source commit %s). DO NOT EDIT DIRECTLY.
-- Requires: X-Ray plugin >= %s; KOReader >= 2026.07 (tested). On an
-- incompatible plugin this patch logs one warning and leaves the stock
-- timeline untouched.

]], PATCH_VERSION, SOURCE_COMMIT, PLUGIN_FLOOR)

local out = table.concat({
    header,
    "local Presence = (function()\n", slurp("src/xray_presencemap.lua"), "\nend)()\n\n",
    "local TRANSLATIONS = (function()\n", slurp("src/translations.lua"), "\nend)()\n\n",
    "local Strip = (function()\n", slurp("src/xray_timeline_strip.lua"), "\nend)()\n\n",
    slurp("src/patch_main.lua"),
})

local f = assert(io.open("patches/2-xray-timeline-presence-map.lua", "w"))
f:write(out)
f:close()
print(string.format("built patches/2-xray-timeline-presence-map.lua (%d bytes)", #out))
