-- Concatenates src/ into patches/2-xray-timeline-presence-map.lua.
-- Run from the repo root: luajit tools/build.lua

local PATCH_VERSION = "2.0.1"
local PLUGIN_FLOOR  = "26.9.4-beta"   -- first release with xray_entity_list.lua, the timeline overlay

local function slurp(path)
    local f = assert(io.open(path, "r"), "missing " .. path)
    local s = f:read("*a")
    f:close()
    return s
end

local header = string.format([[
-- xray-timeline-patch v%s
-- Character presence map and filter for the X-Ray plugin's plot timeline.
-- https://github.com/Pixxel123/xray-timeline-patch
-- Generated by tools/build.lua from src/. DO NOT EDIT DIRECTLY.
-- Requires: X-Ray plugin >= %s; KOReader >= 2026.07 (tested). On an
-- incompatible plugin this patch logs one warning and leaves the stock
-- timeline untouched; older plugins can use release v1.0.0.

]], PATCH_VERSION, PLUGIN_FLOOR)

local out = table.concat({
    header,
    "local Presence = (function()\n", slurp("src/xray_presencemap.lua"), "\nend)()\n\n",
    "local TRANSLATIONS = (function()\n", slurp("src/translations.lua"), "\nend)()\n\n",
    "local Strip = (function()\n", slurp("src/xray_timeline_strip.lua"), "\nend)()\n\n",
    slurp("src/patch_main.lua"),
})

local f = assert(io.open("patches/2-xray-timeline-presence-map.lua", "w"))
f:write(out)
f:close()
print(string.format("built patches/2-xray-timeline-presence-map.lua (%d bytes)", #out))
