-- Regenerates src/translations.lua from a plugin languages/ directory.
-- Usage: luajit tools/extract_translations.lua <languages-dir>
--
-- Replicates the plugin's parsePO (localization_xray.lua) byte-for-byte,
-- including its quirks: no unescaping of \n or \" sequences, non-greedy
-- capture to the first quote. Injected strings must equal what the plugin's
-- own parser produces at runtime, so the state machine below must never be
-- "improved" independently of upstream.

local KEYS = {
    "menu_timeline_all",
    "menu_timeline_presence_map",
    "timeline_no_shared_chapters",
    "timeline_sort_newest",
    "timeline_sort_oldest",
}
local LANGUAGES = {
    "ar", "de", "en", "es", "fr", "hu", "id", "it", "ja",
    "nl", "pl", "pt_br", "ru", "sr", "tr", "uk", "zh_CN",
}

local dir = arg and arg[1]
assert(dir, "usage: extract_translations.lua <languages-dir>")

local function parsePO(filepath)
    local translations = {}
    local file = assert(io.open(filepath, "r"), "cannot open " .. filepath)
    local msgid, msgstr
    local in_msgid, in_msgstr = false, false
    for line in file:lines() do
        if not (line:match("^#") or line:match("^%s*$")) then
            if line:match('^msgid%s+"') then
                if msgid and msgstr then translations[msgid] = msgstr end
                msgid = line:match('^msgid%s+"(.-)"')
                msgstr = nil
                in_msgid, in_msgstr = true, false
            elseif line:match('^msgstr%s+"') then
                msgstr = line:match('^msgstr%s+"(.-)"')
                in_msgid, in_msgstr = false, true
            elseif line:match('^"') then
                local continuation = line:match('^"(.-)"')
                if in_msgid and msgid then msgid = msgid .. continuation
                elseif in_msgstr and msgstr then msgstr = msgstr .. continuation end
            end
        end
    end
    if msgid and msgstr then translations[msgid] = msgstr end
    file:close()
    return translations
end

local out = {
    "-- Generated by tools/extract_translations.lua - DO NOT EDIT.",
    "-- 5 timeline keys x 17 languages, byte-identical to the plugin's .po parse.",
    "return {",
}
for _, lang in ipairs(LANGUAGES) do
    local po = parsePO(dir .. "/" .. lang .. ".po")
    table.insert(out, string.format("    [%q] = {", lang))
    for _, key in ipairs(KEYS) do
        local value = po[key]
        assert(value and value ~= "", lang .. ".po is missing " .. key)
        table.insert(out, string.format("        [%q] = %q,", key, value))
    end
    table.insert(out, "    },")
end
table.insert(out, "}")

local f = assert(io.open("src/translations.lua", "w"))
f:write(table.concat(out, "\n"), "\n")
f:close()
print("wrote src/translations.lua")
